base_url: "https://www.saucedemo.com/"
chromedriver_path: "../drivers/chromedriver/chromedriver"
users:
  standard_user: "standard_user"
  locked_out_user: "locked_out_user"
  problem_user : "problem_user"
  performance_glitch_user : "performance_glitch_user"
  error_user : "error_user"
  visual_user : "visual_user"
password: "secret_sauce"
global_timeout: 2